:sparkles: First chart component
selfdevs/accountability-dashboard pull request #27
Opened 2021-12-20 20:45 UTC by cchampou

2021-12-21 12:10 UTC, oezguerisbert requested changes
Within the chart component I made a suggestion for determining the max-length of displayed data, (automated)

2021-12-21 12:10 UTC, oezguerisbert commented on frontend/src/components/Chart/Chart.tsx
> +  <RumbleChart height={400} width={800} series={series} minY={0} maxY={10} minX={0} maxX={31} className="chart-container">
Can we make the `maX` property as `maxX={maxXPoint}` so its adjusts without hardcoding the value?
like so: 
```jsx
//.... series stuff


//calculation of maximum amount of data within all series.
const maxXPoint = series.map((serie) => serie.data.length).reduce((previousValue, currentValue) => Math.max(previousValue ?? 0, currentValue));

<RumbleChart 
  height={400} 
  width={800} 
  series={series} 
  minY={0} 
  maxY={10} 
  minX={0} 
  maxX={maxXPoint} // <-- here its automated :)
  className="chart-container">
```

This makes sure that how many series will be used, it take the length within the data and displays the entire content.
(I know 31 is max days of Month, but maybe some people just want to use 2 weeks as data :) )

2022-01-04 18:32 UTC, cchampou commented on frontend/src/components/Chart/Chart.tsx
> +  <RumbleChart height={400} width={800} series={series} minY={0} maxY={10} minX={0} maxX={31} className="chart-container">
I simply removed the props since they will be guessed automatically by the data injected. So any number of days will suit.

2022-01-04 22:43 UTC, oezguerisbert approved these changes
LGTM

2022-01-05 18:42 UTC, merged