:sparkles: Discord commands
selfdevs/accountability-dashboard pull request #45
Opened 2022-01-11 00:39 UTC by cchampou

# Work in progress

![Screenshot from 2022-01-10 22-29-29](https://user-images.githubusercontent.com/23266335/148861140-3339fe06-1c7b-45a6-8d8f-14281fa97c4a.png)

2022-01-11 19:11 UTC, M123-dev approved these changes
👍🏼

2022-01-16 13:20 UTC, Juliotati requested changes

2022-01-16 13:20 UTC, Juliotati commented on backend/src/services/entryService.ts
> +    : 'You did not record what you achieved';
Instead of `done` what do you think on `completed` for the text that the user sees?
eg: 
```javascript
`You have completed "${data.done}"`
```
Another question, what is `data.done` holding?
1. Is it the **title** of the goal marked as `done`? or 
2. The total **number** of the goals marked as `done`?

The names are sort of fine but they leave space for lots of questions/different interpretations, so in this case, it's best to have precise names ✨

### If the context is about numbers, examples would be:
1. `totalCompleted`
2. `completedCount`, etc
### If the context is not about numbers, examples could be:
1. `completedTitle` or something more appropriate

2022-01-16 13:20 UTC, Juliotati commented on backend/src/services/discordService.ts
> +    null
I'm guessing `dataValue` is holding a boolean 🤔, but what is `data` & `value` or what is it supposed to represent?
- What I mean by this is that the name `dataValue` is too raw, in the sense that it's not explaining what it represents.
eg:
```javaScript
const dataValue = true;
```
vs
```javaScript
const isSubscribed = true;
```

If it's not holding a boolean, the same still can use some cleaning. The above example could still be of use ✨

2022-01-16 13:37 UTC, cchampou commented on backend/src/services/entryService.ts
> +    : 'You did not record what you achieved';
So, I updated the wording in the string to completed instead of done. For the done variable name, it's a bit complex because it implies renaming in the database also. I added a comment in the model to describe quickly the fields.

2022-01-16 13:42 UTC, Juliotati commented on backend/src/services/entryService.ts
> +    : 'You did not record what you achieved';
Okay✌🏽
We can create an issue to update this later, just for the sake of clarity on the basis of:
_Better to have the code explain itself than writing comments that do the job of the code_

2022-01-16 13:44 UTC, cchampou commented on backend/src/services/discordService.ts
> +    null
So value is basically anything that can fit in either `goal`, `done` or `comment` so a number or a string.

2022-01-16 13:47 UTC, cchampou commented on backend/src/services/discordService.ts
> +    null
I renamed it `userInput`. I also renamed `dataName` to `fieldToUpdate`.

2022-01-16 13:47 UTC, Juliotati commented on backend/src/services/entryService.ts
> +    : 'You did not record what you achieved';
Later also when possible we can improve this to add more minor info and support plurals:
eg:
If `data.done !=== 1`
```typeScript
`You have completed ${data.done} tasks`
```
Other wise
```typeScript
`You have completed ${data.done} task`
```

2022-01-16 13:49 UTC, cchampou commented on backend/src/services/entryService.ts
> +    : 'You did not record what you achieved';
> Okay✌🏽 We can create an issue to update this later, just for the sake of clarity on the basis of: _Better to have the code explain itself than writing comments that do the job of the code_

I agree

2022-01-16 13:50 UTC, Juliotati commented on backend/src/services/discordService.ts
> +    null
yeah much better ✨

2022-01-16 13:51 UTC, cchampou commented on backend/src/services/entryService.ts
> +    : 'You did not record what you achieved';
> Later also when possible we can improve this to add more minor info and support plurals: eg: If `data.done !=== 1`
> 
> ```ts
> `You have completed ${data.done} tasks`
> ```
> 
> Other wise
> 
> ```ts
> `You have completed ${data.done} task`
> ```

Except the fact currently we do not have the unit, so I'm not mentioning `task` because it can be hours, number of push-ups, number of meal self-prepared, whatever.

2022-01-16 13:51 UTC, Juliotati reviewed
LGTM

2022-01-16 13:52 UTC, Juliotati approved these changes

2022-01-16 17:23 UTC, merged