:memo: Front-end env documentation
selfdevs/accountability-dashboard pull request #61
Opened 2022-01-12 19:34 UTC by cchampou

# Start with front-end development documentation

Add some explanations about environment variables in front-end folder. It gives values to work with the preview API and only focus on task without having to start a local API.

2022-01-15 23:51 UTC, Juliotati requested changes

2022-01-15 23:51 UTC, Juliotati commented on frontend/README.md
> +forget the / at the end.
```
"Don't forget the / at the end."
```
Is something important, what you do think about having it on a new line and in _italics_

2022-01-15 23:51 UTC, Juliotati commented on frontend/README.md
> +preview API and start developing immediately.
An alternative for this point:
- `REACT_APP_API_BASE_URL`: API base URL.
  - Continue using `https://ziro.cchampou.me/api` if you want the preview API and start developing immediately.
  
pick one for the above, _"Continue using... or Use the default..._"

2022-01-16 00:06 UTC, cchampou commented on frontend/README.md
> +forget the / at the end.
Newline & italic + bold, more visible now.

2022-01-16 00:09 UTC, Juliotati approved these changes

2022-01-16 12:10 UTC, merged