✨ Solves #63 #83
selfdevs/accountability-dashboard pull request #87
Opened 2022-02-16 14:15 UTC by ArthThapa

This PR achieves the following:

### Features

- 💫There is now confirmation before deleting entry. Solves #63 
- 💫New token system, user will stay logged until discord token is expires , 1 week (TODO: refresh discord's token). Partially solves #83 

### Improvements

- 💫On getting new discordCredentials, older ones will be deleted. (Suggestion: delete current discordCredentials for everyone and reset their login in production DB in order to efficiently adapt.)
- 💫Remove unnecessary dependencies.
- 💫Revamp Current auth flow, using axios interceptors to achieve fetching/injection of tokens.
- 💫Rewrote IO functions to prevent misspells.

2022-02-16 20:03 UTC, cchampou commented on backend/src/routers/auth.ts
> +export interface userPayload extends JwtPayload {
PascalCase the interface's name :wink:

2022-02-16 20:05 UTC, cchampou commented on backend/src/routers/auth.ts
> +    if (tokenDoc) await tokenDoc.delete();
Why not use directly the `deleteOne` from Mongoose? :slightly_smiling_face:

2022-02-16 20:09 UTC, cchampou commented on backend/src/services/discordService.ts
> +    await prevCredentials.delete();
Same here you can probably use `deleteOne` :wink:

2022-02-16 20:12 UTC, cchampou commented on frontend/package.json
> +    "@types/react-router-dom": "^5.3.3",
❌ Warning remove this package, this is for `react-router-dom@5`, the v6 is shipped with types built-in :rocket:

2022-02-16 20:14 UTC, cchampou commented on frontend/src/components/EntryEditor/EntryEditor.tsx
> +import instance from '../../modules/http/axiosClient';
It may be super to find a more accurate name than "instance", it can be confusing since could be anything. :left_speech_bubble:

2022-02-16 20:16 UTC, cchampou commented on frontend/src/components/Table/hooks.ts
> +      )
Smart cheap solution :joy: :moneybag:

2022-02-16 20:20 UTC, cchampou commented on frontend/src/modules/http/axiosClient.ts
> +            addAccessToken((data as TokenResponse).accessToken);
```typescript
instance.post<TokenResponse>('/auth/token').then(.......
```
If you write it this way, Axios will return you wonderful already typed data :sparkles: 
So you don't have to do those `as`, try to avoid them all :wink:

2022-02-16 20:23 UTC, cchampou reviewed
That's **awesome** @ArthThapa congratulations! Just waiting you fix the comment about types dependencies `react-router-dom`, because it's important, to give my final approval but ... :clap: :1st_place_medal:

2022-02-17 02:38 UTC, ArthThapa commented on frontend/src/components/Table/hooks.ts
> +      )
I know right 🤣

2022-02-17 02:45 UTC, ArthThapa commented
😁

2022-02-17 09:14 UTC, cchampou approved these changes
Ohhhhh yeah :rocket: :guitar: :100:

2022-02-17 15:19 UTC, Juliotati commented on frontend/src/components/EditableTitle/EditableTitle.tsx
>        setEditMode(false);
Sweet ✨

2022-02-17 15:25 UTC, ArthThapa commented on frontend/src/components/EditableTitle/EditableTitle.tsx
>        setEditMode(false);
?

2022-02-17 15:28 UTC, Juliotati requested changes

2022-02-17 15:28 UTC, Juliotati commented on backend/src/services/discordService.ts
> +    await DiscordCredentials.deleteOne({ _id: user.discordCredentials }).catch(
if
```typeScript
await User.findOne({ email: discordUser.email });
```
returns a boolean, then it's better to have a more descriptive name holding the final value.

instead of naming it `user`, prefer:
`hasUser` or `foundUser`.

```typeScript
const hasUser = await User.findOne({ email: discordUser.email });
  if (hasUser) {
   // the rest
  }
```

the current name `user` implies that here you have the whole `user` object, if that's the case then we can ignore this change request 👌🏽

2022-02-17 15:30 UTC, ArthThapa commented on backend/src/services/discordService.ts
> +    await DiscordCredentials.deleteOne({ _id: user.discordCredentials }).catch(
It returns the user object 🟢

2022-02-17 15:30 UTC, Juliotati commented on frontend/src/components/EditableTitle/EditableTitle.tsx
>        setEditMode(false);
got rid of `_.noop`

2022-02-17 15:31 UTC, ArthThapa commented on frontend/src/components/EditableTitle/EditableTitle.tsx
>        setEditMode(false);
heh got rid of `lodash` 😁

2022-02-17 15:35 UTC, Juliotati commented on backend/src/services/discordService.ts
> +    await DiscordCredentials.deleteOne({ _id: user.discordCredentials }).catch(
Cool nice, so what is that `if statement` checking?
If the object it not `null`?

2022-02-17 15:37 UTC, ArthThapa commented on backend/src/services/discordService.ts
> +    await DiscordCredentials.deleteOne({ _id: user.discordCredentials }).catch(
yes, if there is an object

2022-02-17 15:39 UTC, Juliotati approved these changes
Great! LGTM

2022-02-18 08:46 UTC, merged